apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app.kubernetes.io/name: keycloak-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: identity
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak-db
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
