apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gregorie769-dev
resources:
  - ../../base
images:
  - name: donation-api
    newName: image-registry.openshift-image-registry.svc:5000/gregorie769-dev/donation-api
    # Ligne mise a jour automatiquement par Jenkins (stage "Update GitOps") : ne pas editer a la main
    newTag: 1.1.0-SNAPSHOT-1278a5b-b24
