apiVersion: v1
kind: Service
metadata:
  name: otel-lgtm
  labels:
    app.kubernetes.io/name: otel-lgtm
    app.kubernetes.io/part-of: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
      protocol: TCP
    # OTLP : interne au namespace uniquement (pas de Route)
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
